### ISSUE TITLE
Nr. 4, Aufgabe 1B User Stories

### ISSUE THREAD

**Issue by blueImoon** [IWCBN/codes-se1-ws24#15]
# Aufgabe 1B
#### Acht aussagekräftige User Stories
  a) INVEST-Eigenschaften, Epics zuordnen
  b) plausible Mehrwertschätzungen, denkbare Aufwandsschätzungen (Fibonnacci-Zahl)
  c) verifizierbaren Akzeptanzkriterien (mindestens zwei pro user story)
  (d) Definition-of-Ready ableiten)

**Comment by blueImoon** [comment]
User Case 1 fertig

**Comment by ki-fer** [comment]
Als Gruppe heute besprechen.
Aktuelle Version auf Nextcloud.
